export const habitats ={
"A3":"Infralittoral rock and other hard substrata",
"A3.1":"Atlantic and Mediterranean high energy infralittoral rock",
"A3.2":"Atlantic and Mediterranean moderate energy infralittoral rock",
"A3.3":"Atlantic and Mediterranean low energy infralittoral rock",
"A3.31":"Silted kelp on low energy infralittoral rock with full salinity",
"A4":"Circalittoral rock and other hard substrata",
"A4.1":"Atlantic and Mediterranean high energy circalittoral rock",
"A4.11/13":"",
"A4.12":"Sponge communities on deep circalittoral rock",
"A4.2":"Atlantic and Mediterranean moderate energy circalittoral rock",
"A4.2/3":"",
"A4.26":"Mediterranean coralligenous communities moderately exposed to hydrodynamic action",
"A4.26/32":"",
"A4.27":"Faunal communities on deep moderate energy circalittoral rock",
"A4.3":"Atlantic and Mediterranean low energy circalittoral rock",
"A4.31":"Brachiopod and ascidian communities on circalittoral rock",
"A4.33":"Faunal communities on deep low energy circalittoral rock",
"A5":"Sublittoral sediment",
"A5.1":"Sublittoral coarse sediment",
"A5.11":"Infralittoral coarse sediment in low or reduced salinity",
"A5.13":"Infralittoral coarse sediment",
"A5.14":"Circalittoral coarse sediment",
"A5.15":"Deep circalittoral coarse sediment",
"A5.2":"Sublittoral sand",
"A5.23":"Infralittoral fine sand",
"A5.23/24":"",
"A5.24":"Infralittoral muddy sand",
"A5.25":"Circalittoral fine sand",
"A5.25/26":"",
"A5.26":"Circalittoral muddy sand",
"A5.27":"Deep circalittoral sand",
"A5.3":"Sublittoral mud",
"A5.33":"Infralittoral sandy mud",
"A5.33/34":"",
"A5.34":"Infralittoral fine mud",
"A5.35":"Circalittoral sandy mud",
"A5.35/36":"",
"A5.36":"Circalittoral fine mud",
"A5.37":"Deep circalittoral mud",
"A5.38":"Mediterranean communities of muddy detritic bottoms",
"A5.39":"Mediterranean communities of coastal terrigenous muds",
"A5.4":"Sublittoral mixed sediments",
"A5.43":"Infralittoral mixed sediments",
"A5.44":"Circalittoral mixed sediments",
"A5.45":"Deep circalittoral mixed sediments",
"A5.46":"Mediterranean animal communities of coastal detritic bottoms",
"A5.47":"Mediterranean communities of shelf-edge detritic bottoms",
"A5.5":"Sublittoral macrophyte-dominated sediment",
"A5.51":"Maerl beds",
"A5.53":"Sublittoral seagrass beds",
"A6":"Deep-sea bed",
"A6.1":"Deep-sea rock and artificial hard substrata",
"A6.11":"Deep-sea bedrock",
"A6.2":"Deep-sea mixed substrata",
"A6.3":"Deep-sea sand",
"A6.3/4":"",
"A6.4":"Deep-sea muddy sand",
"A6.5":"Deep-sea mud",
"A6.7":"Raised features of the deep-sea bed",
"A6.71":"Permanently submerged flanks of oceanic islands",
"A6.72":"Seamounts, knolls and banks",
"A6.73":"Oceanic ridges",
"A6.74":"Abyssal hills",
"A6.8":"Deep-sea trenches and canyons, channels, slope failures and slumps on the continental slope"
}